version: '3.9'

services:
  prometheus:
    image: ${PROMETHEUS_DOCKER_IMAGE}
    container_name: ${APP_NAME}_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT}:9090"
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: ${APP_NAME}_grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prometheus_data:

networks:
  default:
    name: ${APP_NAME}_monitoring
